# Generated by Django 4.2.11 on 2026-04-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Без названия', max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_index', models.IntegerField(default=0)),
                ('paragraph_text', models.TextField(blank=True)),
                ('positive_score', models.FloatField(default=0.0)),
                ('negative_score', models.FloatField(default=0.0)),
                ('neutral_score', models.FloatField(default=0.0)),
                ('compound_score', models.FloatField(default=0.0)),
                ('text_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='analyzer.textsample')),
            ],
            options={
                'ordering': ['paragraph_index'],
            },
        ),
        migrations.CreateModel(
            name='LexicalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.IntegerField(default=0)),
                ('unique_words', models.IntegerField(default=0)),
                ('flesch_reading_ease', models.FloatField(blank=True, null=True)),
                ('word_frequency', models.JSONField(default=dict)),
                ('text_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lexical', to='analyzer.textsample')),
            ],
        ),
    ]
